CREATE TABLE IF NOT EXISTS species (
  species_id SERIAL PRIMARY KEY,
  species_string VARCHAR(32)
);

INSERT INTO species (species_string) VALUES
  ('Anchoveta'),
  ('Anguila'),
  ('Atún aleta amarilla'),
  ('Bonito'),
  ('Caballa'),
  ('Cabrilla'),
  ('Cachema'),
  ('Cágalo'),
  ('Calamar'),
  ('Cangrejo'),
  ('Caracol'),
  ('Caracol negro'),
  ('Caracol pirulino'),
  ('Carajito'),
  ('Cavinza'),
  ('Chabelo'),
  ('Cherlo'),
  ('Chiri'),
  ('Chita'),
  ('Cojinova'),
  ('Concha de abanico'),
  ('Congrio'),
  ('Congrio gato'),
  ('Doncella'),
  ('El colorado'),
  ('Espejo'),
  ('Falso volador'),
  ('Guitarra'),
  ('Jurel'),
  ('Langosta'),
  ('Langostino'),
  ('Lenguado'),
  ('Lisa'),
  ('Lomo negro'),
  ('Machete'),
  ('Merluza'),
  ('Mero'),
  ('Móbula'),
  ('Palmerona'),
  ('Palabritas'),
  ('Pampanito'),
  ('Pava'),
  ('Peje gallo'),
  ('Pejeblanco'),
  ('Perico'),
  ('Pez diablo'),
  ('Pez espada'),
  ('Pintadilla'),
  ('Pota'),
  ('Pulpo'),
  ('Rayas'),
  ('Sierra'),
  ('Suco'),
  ('Tiburon azul'),
  ('Tiburón blanco'),
  ('Tollo'),
  ('Tiburon zorro'),
  ('Tramboyo'),
  ('Volador'),
  ('Yarro')
;